import Head from 'next/head'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Isaac Fernández Navarro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 class='font-xl'>Isaac</h1>
      <h2 className='p-5'>Isaac</h2>
      <h3 className='p-5'>Isaac</h3>
    </>
  )
}
